const $=s=>document.querySelector(s);
async function api(url,opt={}){let r=await fetch(url,{headers:{"Content-Type":"application/json"},...opt});let d=await r.json();if(!r.ok)throw Error(d.error||"Error");return d}
async function login(){try{await api("/api/login",{method:"POST",body:JSON.stringify({username:$("#user").value,password:$("#pass").value})});$("#login").classList.add("hidden");$("#app").classList.remove("hidden");show("content")}catch(e){alert(e.message)}}
async function logout(){await api("/api/logout",{method:"POST"});location.reload()}
function show(x){["content","buttons","diary"].forEach(k=>$("#"+k).classList.toggle("hidden",k!==x));$("#title").textContent=x==="content"?"Site Content":x[0].toUpperCase()+x.slice(1);if(x==="content")loadContent();if(x==="buttons")loadButtons();if(x==="diary")loadDiary()}
async function loadContent(){let c=await api("/api/admin/content");$("#content").innerHTML=`<div class="panel"><div class="grid">${Object.entries(c).map(([k,v])=>`<div class="field"><label>${k}</label><input data-key="${k}" value="${String(v).replace(/"/g,"&quot;")}"></div>`).join("")}</div><button class="save" onclick="saveContent()">Save All Changes</button></div>`}
async function saveContent(){let o={};document.querySelectorAll("[data-key]").forEach(x=>o[x.dataset.key]=x.value);await api("/api/admin/content",{method:"PUT",body:JSON.stringify(o)});alert("Saved")}
async function loadButtons(){let a=await api("/api/admin/buttons");$("#buttons").innerHTML=`<div class="panel"><h2>Add Button</h2><div class="grid"><input id="bl" placeholder="Button label"><input id="bu" placeholder="URL e.g. #about"><input id="bi" placeholder="Icon" value="→"><input id="bc" placeholder="Location e.g. hero"><input id="bo" placeholder="Order" value="1"></div><button class="save" onclick="addButton()">Add Button</button></div><div class="panel"><h2>Manage Buttons</h2>${a.map(x=>`<div class="item"><div class="row"><input id="l${x.id}" value="${x.label}"><input id="u${x.id}" value="${x.url}"><input id="o${x.id}" value="${x.sort_order}"></div><p>Icon: <input id="i${x.id}" value="${x.icon}"> &nbsp; Location: <input id="c${x.id}" value="${x.location}"></p><button class="mini" onclick="editButton(${x.id})">Save</button> <button class="danger" onclick="delButton(${x.id})">Delete</button></div>`).join("")}</div>`}
async function addButton(){await api("/api/admin/buttons",{method:"POST",body:JSON.stringify({label:$("#bl").value,url:$("#bu").value,icon:$("#bi").value,location:$("#bc").value,sort_order:$("#bo").value})});loadButtons()}
async function editButton(id){await api("/api/admin/buttons/"+id,{method:"PUT",body:JSON.stringify({label:$("#l"+id).value,url:$("#u"+id).value,icon:$("#i"+id).value,location:$("#c"+id).value,sort_order:$("#o"+id).value,visible:1})});loadButtons()}
async function delButton(id){if(confirm("Delete this button?")){await api("/api/admin/buttons/"+id,{method:"DELETE"});loadButtons()}}
async function loadDiary(){let a=await api("/api/admin/diary");$("#diary").innerHTML=`<div class="panel"><h2>Add Chapter</h2><div class="grid"><input id="dc" placeholder="CHAPTER 03"><input id="dt" placeholder="Title"><input id="dd" placeholder="Date"><input id="de" placeholder="Short excerpt"><textarea id="db" placeholder="Full diary text"></textarea><input id="do" placeholder="Order" value="1"></div><button class="save" onclick="addDiary()">Add Chapter</button></div><div class="panel"><h2>Manage Diary</h2>${a.map(x=>`<div class="item"><input id="tc${x.id}" value="${x.chapter}"><input id="tt${x.id}" value="${x.title}"><input id="td${x.id}" value="${x.date_text}"><textarea id="tb${x.id}">${x.body}</textarea><button class="mini" onclick="editDiary(${x.id})">Save</button> <button class="danger" onclick="delDiary(${x.id})">Delete</button></div>`).join("")}</div>`}
async function addDiary(){await api("/api/admin/diary",{method:"POST",body:JSON.stringify({chapter:$("#dc").value,title:$("#dt").value,date_text:$("#dd").value,excerpt:$("#de").value,body:$("#db").value,sort_order:$("#do").value})});loadDiary()}
async function editDiary(id){await api("/api/admin/diary/"+id,{method:"PUT",body:JSON.stringify({chapter:$("#tc"+id).value,title:$("#tt"+id).value,date_text:$("#td"+id).value,body:$("#tb"+id).value,visible:1,sort_order:1})});loadDiary()}
async function delDiary(id){if(confirm("Delete this chapter?")){await api("/api/admin/diary/"+id,{method:"DELETE"});loadDiary()}}
api("/api/me").then(x=>{if(x.loggedIn){$("#login").classList.add("hidden");$("#app").classList.remove("hidden");loadContent()}})
